sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_install:
  - npm i -g npm@^6
before_script:
  - npm prune
script:
  - npm run build
after_success:
  if: branch = master
  - npm run report-coverage
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
