name: Euclidean Rhythms Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  'build-and-deploy':
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test & Build
        run: npm run build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
