name: Euclidean Rhythms Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3

      - run: npm prune
      - run: npm run build

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v2

      - run: npm run semantic-release
